# SonarCloud Automatic Analysis Configuration
# See: https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/automatic-analysis/#additional-analysis-configuration

sonar.organization=hous3-digital
sonar.projectKey=<projectKey>

# Source encoding
sonar.sourceEncoding=UTF-8

# Path to sources
sonar.sources=app
# sonar.inclusions=

# Exclusions
sonar.exclusions=app/node_modules/**,**/*.sql,**/*.md,**/inputs/**,**/common/*.output.ts,**/mappers/**

# Path to tests
sonar.tests=app/__tests__
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts,**/__tests__/**

# Exclusions for copy-paste detection
sonar.cpd.exclusions=app/node_modules,app/dist

# Coverage report path
sonar.typescript.lcov.reportPaths=app/coverage/lcov.info