name: feature-workflow

on:
  push:
    branches:
      - feat/**
      - chore/**
      - fix/**
      - task/**

permissions:
  pull-requests: write
  contents: write
  repository-projects: write

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: "24"

      - run: cd app && yarn

      - name: Upload node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - run: |
          cd app
          yarn
          yarn prisma:generate
          yarn lint

  pull-request:
    name: Open PR
    needs: [terraform-ci, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${{ github.ref_name }}

          pr_number=$(gh pr list --state open --head ${{ github.ref_name }} --base staging --json number -q '.[].number')
          sleep 4
          if [ -n "$pr_number" ]; then
            echo "GOING TO EDIT CURRENT PR"
            gh pr edit $pr_number \
              --title "PR: ${{ github.ref_name }} -> staging" \

          else 
            echo "GOING TO CREATE PR"
              gh pr create \
              --title "PR: ${{ github.ref_name }} -> staging" \
              --body-file .github/pull_request_template.md \
              --head ${{ github.ref }} \
              --base staging 
          fi
