name: feature-workflow

on:
  push:
    branches:
      - feat/**
      - chore/**
      - fix/**
      - task/**

permissions:
  pull-requests: write
  contents: write
  repository-projects: write

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: "24"

      - run: cd app && yarn

      - name: Upload node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - run: |
          cd app
          yarn
          yarn prisma:generate
          yarn lint

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - run: |
          cd app
          yarn
          yarn audit --level high --groups dependencies

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - run: |
          cd app
          yarn
          yarn prisma:generate
          yarn test

  terraform-ci:
    name: Terraform CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.14.0"

      - name: Navigate to Terraform folder
        run: |
          cd infra/terraform

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Linting
        id: linting
        run: echo Linting

      - name: Security Scan
        id: security-scan
        if: false
        uses: aquasecurity/tfsec-action@v1.0.0

  pull-request:
    name: Open PR
    needs: [terraform-ci, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${{ github.ref_name }}

          pr_number=$(gh pr list --state open --head ${{ github.ref_name }} --base staging --json number -q '.[].number')
          sleep 4
          if [ -n "$pr_number" ]; then
            echo "GOING TO EDIT CURRENT PR"
            gh pr edit $pr_number \
              --title "PR: ${{ github.ref_name }} -> staging" \

          else 
            echo "GOING TO CREATE PR"
              gh pr create \
              --title "PR: ${{ github.ref_name }} -> staging" \
              --body-file .github/pull_request_template.md \
              --head ${{ github.ref }} \
              --base staging 
          fi
